// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozkuefljvpzpmbrkknfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96a3VlZmxqdnB6cG1icmtrbmZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NzE2NzIsImV4cCI6MjA2OTM0NzY3Mn0.2SXI4yjzIQ0P8GE_bZtHIbrvkfmcHAAqDU81_gW9Wqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});